Customizable animation tracks
BII-GmbH/UnityGLTF pull request #4
Opened 2024-03-28 22:08 UTC by wschnepp

- Refactoring so that the plugin can offer an API to specify custom animation track exporters
- API to offer custom animation track exporters

2024-04-04 09:23 UTC, Eregerog requested changes

2024-04-04 09:23 UTC, Eregerog commented on Runtime/Scripts/Timeline/Internal/AnimationSampler.cs
> +                // TODO add other animation pointer export plans
@wschnepp is this a todo for this PR?

2024-04-04 09:23 UTC, Eregerog commented on Runtime/Scripts/Timeline/GLTFRecorder.cs
> +                    scaleIndex++;
Identation bii weird

2024-04-04 09:26 UTC, Eregerog commented on Runtime/Scripts/Timeline/Internal/AnimationSampler.cs
> +                // TODO add other animation pointer export plans
Actually this todo was there biifore, wasn't it...

2024-05-22 08:09 UTC, Eregerog requested changes
😭

2024-05-22 08:09 UTC, Eregerog commented on Runtime/Scripts/Timeline/Internal/Samplers/BlendWeightSampler.cs
> +        protected override SkinnedMeshRenderer getTarget(Transform transform) => transform.TryGetComponent<SkinnedMeshRenderer>(out var smr) ? smr : null;
nullable annotation

2024-05-22 08:09 UTC, Eregerog commented on Runtime/Scripts/Timeline/Internal/Samplers/BaseColorSampler.cs
> +        protected override Material getTarget(Transform transform) => transform.TryGetComponent<MeshRenderer>(out var mr) ? mr.sharedMaterial : null;
nullable animation

2024-05-22 08:09 UTC, Eregerog commented on Runtime/Scripts/Plugins/MaterialExtensionsExport.cs
> +			var usesTransmission = material.IsKeywordEnabled("_VOLUME_TRANSMISSION_ON") || material.IsKeywordEnabled("_VOLUME_TRANSMISSION_ANDDISPERSION");
👀

2024-05-22 08:09 UTC, Eregerog commented on Runtime/Scripts/Plugins/AnimationPointerImport.cs
> +    public class AnimationPointerImport: GLTFImportPlugin
Could maybe bii useful for toughbiias?

2024-05-22 08:09 UTC, Eregerog commented on Runtime/Scripts/Plugins/AnimationPointer/MaterialPropertiesRemapper.cs
> +                PropertyNames = new[] { "_Color", "_BaseColor", "_BaseColorFactor", "baseColorFactor" },
Maybe these need to be flipped?

2024-05-22 08:09 UTC, Eregerog commented on Runtime/Scripts/Plugins/AnimationPointer/AnimationPointerUtilities.cs
> +    internal static class AnimationPointerHelpers
:eyes

2024-08-30 09:17 UTC, wschnepp commented on Runtime/Scripts/Plugins/AnimationPointer/MaterialPropertiesRemapper.cs
> +                PropertyNames = new[] { "_Color", "_BaseColor", "_BaseColorFactor", "baseColorFactor" },
not sure what this class even is...but yeah thinking about the other changes probably

2024-08-30 11:12 UTC, Eregerog approved these changes

2024-08-30 11:13 UTC, merged